# Generated by Django 4.2.11 on 2024-08-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weaeinkauf', '0005_servicepreis_alt_id_weapreis_alt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quelle',
            name='quellenart',
            field=models.CharField(choices=[('Vertrag', 'Vertrag'), ('Schätzung', 'Schätzung'), ('Indikation', 'Indikation'), ('Angebot', 'Angebot'), ('', '')], default='', max_length=200),
        ),
    ]
